stages:
  - build
  - test

variables:
  CI_REGISTRY_IMAGE: "shormario/gps_g33"
  CI_REGISTRY: "registry.gitlab.com"

build-job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - export DOCKER_TAG=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    - export DOCKER_TAG_LATEST=$CI_COMMIT_REF_SLUG-latest
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG .
    - docker tag $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG_LATEST
    - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG
    - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG_LATEST
  only:
    - qa
    - main

unit-test-job:
  stage: test
  script:
    - echo "Replace with the command to run unit tests"

sonarcloud-job:
  stage: test
  script:
    - echo "Replace with the script provided by sonarcloud"
